'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const t=(ar,en)=>lang==='ar'?ar:en;
let lang='ar';try{lang=localStorage.getItem('samra-language')==='en'?'en':'ar'}catch{}
const PHONE='966599721275';
const wa=text=>'https://wa.me/'+PHONE+'?text='+encodeURIComponent(text);
const svg=(body,cls='')=>`<svg class="${cls}" viewBox="0 0 120 120" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
const icons={
 v60:svg('<path d="M25 30h70L65 75H55L25 30ZM35 78h50M43 85v20h34V85M94 35c20-5 15 22-10 20M35 40l23 29M51 37l9 30M75 38L63 68"/>'),
 espresso:svg('<path d="M25 20h70v64H25zM36 33h48v18H36zM20 93h80M44 72v13h27V72M71 73c18-7 15 13 0 9M44 60h25M57 60v6"/>'),
 aeropress:svg('<path d="M42 15h36M48 15v22M72 15v22M36 38h48v48H36zM30 87h60M43 94v14h34V94M56 44v31M69 45h8M69 55h8M69 65h8"/>'),
 chemex:svg('<path d="M30 16h60L70 51l-3 11 29 38q5 10-9 10H33q-14 0-9-10l29-38-3-11L30 16ZM51 54h19M51 64h18M34 91h53"/>'),
 french:svg('<path d="M30 31h52v73H30zM25 30h62M56 30V12M46 12h20M37 82h38M56 38v42M83 42h16v44H84"/>'),
 cold:svg('<path d="M34 24h52v78q0 9-12 9H46q-12 0-12-9V24ZM31 17h58v8H31zM35 57h50M48 70h9v9h-9zM68 90h8v8h-8zM62 43l8-8"/>'),
 rinse:svg('<path d="M26 55h68L65 98H55L26 55ZM42 11h30l-6 20H46l-4-20M54 34v9M65 37v9M45 36v8M35 65l20 25M83 65L65 90"/>'),
 bloom:svg('<path d="M25 42h70L65 91H55L25 42ZM34 54h51M44 20l-2 8M62 13v10M78 20l3 8"/><circle cx="48" cy="62" r="3"/><circle cx="66" cy="58" r="4"/><circle cx="60" cy="75" r="3"/>'),
 pour:svg('<path d="M70 15q-20-3-24 15l19 12 24-17-19-10ZM48 31 29 49M28 52v15M20 71h67L62 108H47L20 71Z"/><path d="M34 83q15-12 37 0M43 91q9-7 19 0"/>'),
 taste:svg('<path d="M30 50h50v36q0 19-25 19T30 86V50ZM80 58q26-6 26 12T80 84M24 110h63M42 35c-12-13 13-13 0-27M61 35c-12-13 13-13 0-27"/>')
};
const botanical=(variant=0)=>svg(`<path d="M61 113C49 90 77 65 56 9" stroke-width="1.5"/><path d="M57 34C10 43 21 7 55 21M62 54C103 54 107 16 64 33M60 77C12 75 16 40 62 58M57 96C101 101 104 63 61 78" fill="currentColor" stroke="none"/><ellipse cx="${variant%2?39:82}" cy="${variant%2?100:17}" rx="9" ry="13" transform="rotate(30 60 60)" fill="currentColor" opacity=".55"/>`,'origin-art');
const coffees=[
{id:'guji',name:['قوجي','Guji'],country:['إثيوبيا','Ethiopia'],code:'ET',color:'#dce5b5',ink:'#4e603c',tags:[['زهري','Floral'],['فاكهي','Fruity'],['حلاوة','Sweet']],group:'floral',method:'v60',desc:['بداية لمحبي القهوة العطرية والأكواب الواضحة. جرّب الترشيح بنسبة أخف لتمنح النكهات مساحة للظهور.','A starting point for aromatic, expressive cups. Try a gentler filter ratio to give the flavour room to open up.']},
{id:'shalshali',name:['شلشلي','Shalshali'],country:['إثيوبيا','Ethiopia'],code:'ET',color:'#e7ced2',ink:'#8a525a',tags:[['فاكهي','Fruity'],['زهري','Floral'],['ناعم','Delicate']],group:'floral',method:'v60',desc:['اكتشف الجانب الخفيف والعطري من القهوة. ابدأ بصبّات هادئة وطحن متوسّط، وتذوّق الكوب حين يبرد قليلاً.','Explore coffee’s delicate, aromatic side. Start with gentle pours and a medium grind, then taste again as the cup cools.']},
{id:'bombe',name:['سيدامو بومبي','Sidamo Bombe'],country:['إثيوبيا','Ethiopia'],code:'ET',color:'#ead5b0',ink:'#806342',tags:[['حلو','Sweet'],['فاكهي','Fruity'],['متوازن','Balanced']],group:'balanced',method:'v60',desc:['خيار لاكتشاف التوازن بين الحلاوة والحيوية. ابدأ بوصفة V60 المتوازنة، ثم عدّل الطحن قليلاً في كل تجربة.','A way into a sweet, lively cup. Start with the balanced V60 recipe, then make small grind adjustments from one brew to the next.']},
{id:'excelso',name:['كولومبيا إكسلسو','Colombia Excelso'],country:['كولومبيا','Colombia'],code:'CO',color:'#c6d7d1',ink:'#3d665c',tags:[['كاكاو','Cocoa'],['حلاوة','Sweet'],['مع الحليب','With milk']],group:'balanced',method:'espresso',desc:['بداية عملية للإسبريسو ولمشروبات الحليب. اضبط الاستخلاص أولاً، ثم أضف الحليب تدريجياً لتحافظ على حضور القهوة.','A practical starting point for espresso and milk drinks. Dial in the shot first, then add milk gradually to keep the coffee present.']},
{id:'mogiana',name:['البرازيل موجيانا','Brazil Mogiana'],country:['البرازيل','Brazil'],code:'BR',color:'#d9c4a5',ink:'#755537',tags:[['مكسرات','Nutty'],['كاكاو','Cocoa'],['قوام غني','Full body']],group:'rich',method:'espresso',desc:['لمن يبحث عن كوب غني ومريح. جرّبه كإسبريسو أو مع الحليب، أو استخدم الفرنش برس لاستكشاف القوام.','For a comforting, fuller cup. Explore it as espresso, pair it with milk, or try a French press to focus on body.']},
{id:'drugar',name:['أوغندا دروغار','Uganda Drugar'],country:['أوغندا','Uganda'],code:'UG',color:'#d0c7d8',ink:'#63516e',tags:[['غني','Rich'],['كاكاو','Cocoa'],['فاكهة داكنة','Dark fruit']],group:'rich',method:'french',desc:['اتجاه لمحبي النكهة العميقة والقوام الممتلئ. جرّب النقع بالفرنش برس، ثم قارن النتيجة مع الترشيح الورقي.','A direction for deeper flavours and a fuller mouthfeel. Try immersion in a French press, then compare it with a paper-filtered brew.']}
];
const bi=a=>a[lang==='ar'?0:1];
let filter='all',method='v60',dose=20,style='balanced',quizStep=0,answers=[],cart=[];
try{const saved=JSON.parse(localStorage.getItem('samra-cart')||'[]');if(Array.isArray(saved))cart=saved.filter(x=>x&&coffees.some(c=>c.id===x.id)).map(x=>({id:x.id,qty:Math.min(20,Math.max(1,parseInt(x.qty)||1)),grind:['whole','filter','espresso','press'].includes(x.grind)?x.grind:'whole'}))}catch{}
const grindOptions=()=>[['whole',t('حبوب كاملة','Whole beans')],['filter',t('طحن للفلتر','Filter grind')],['espresso',t('طحن للإسبريسو','Espresso grind')],['press',t('طحن للفرنش برس','French press grind')]];
const methodNames=()=>({v60:'V60',espresso:t('إسبريسو','Espresso'),aeropress:'AeroPress',chemex:'Chemex',french:t('فرنش برس','French press'),cold:t('كولد برو','Cold brew')});
function saveCart(){try{localStorage.setItem('samra-cart',JSON.stringify(cart))}catch{}$('#cartCount').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(notify.timeout);notify.timeout=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function addCart(id){const item=cart.find(x=>x.id===id);if(item)item.qty=Math.min(20,item.qty+1);else cart.push({id,qty:1,grind:'whole'});saveCart();notify(t('أُضيف إلى اختياراتك','Added to your selection'));renderCart()}
function renderCollection(){const filters=[['all',t('كل المحاصيل','All coffees')],['floral',t('زهري وفاكهي','Floral & fruity')],['balanced',t('حلو ومتوازن','Sweet & balanced')],['rich',t('غني وممتلئ','Rich & full')]];$('#filters').innerHTML=filters.map(([v,l])=>`<button data-filter="${v}" aria-pressed="${v===filter}" class="${v===filter?'active':''}">${l}</button>`).join('');$('#coffeeGrid').innerHTML=coffees.filter(c=>filter==='all'||c.group===filter).map(c=>`<article class="coffee-card"><button class="coffee-art" data-detail="${c.id}" aria-label="${t('اكتشف','Explore')} ${bi(c.name)}" style="--tone:${c.color};--art-ink:${c.ink}"><span class="art-top"><span>SAMRA / ORIGIN SERIES</span><span>0${coffees.indexOf(c)+1}</span></span>${botanical(coffees.indexOf(c))}<span class="art-bottom" dir="ltr">${c.name[1].replace('Colombia ','').replace('Brazil ','').replace('Uganda ','')}</span><span class="art-country">${c.country[1].toUpperCase()} / ${c.code}</span></button><div class="coffee-info"><p class="coffee-origin">${bi(c.country)} · ${methodNames()[c.method]}</p><h3>${bi(c.name)}</h3><div class="flavour-tags">${c.tags.map(a=>`<span>${bi(a)}</span>`).join('')}</div><div class="coffee-actions"><button class="detail-link" data-detail="${c.id}">${t('اكتشف المحصول ←','Meet this coffee →')}</button><button class="add-button" data-add="${c.id}" aria-label="${t('أضف','Add')} ${bi(c.name)}">+</button></div></div></article>`).join('')}
function showDetail(id){const c=coffees.find(x=>x.id===id);$('#coffeeDetail').innerHTML=`<div class="detail-art" style="--tone:${c.color};--art-ink:${c.ink}">${botanical(coffees.indexOf(c))}</div><p class="eyebrow">${bi(c.country)} / SAMRA COLLECTION</p><h2>${bi(c.name)}</h2><div class="flavour-tags">${c.tags.map(a=>`<span>${bi(a)}</span>`).join('')}</div><p class="detail-description">${bi(c.desc)}</p><div class="detail-facts"><div><small>${t('جرّبه مع','TRY IT WITH')}</small><b>${methodNames()[c.method]}</b></div><div><small>${t('الدفعة الحالية','CURRENT LOT')}</small><b>${t('اسألنا عن التحميص والمعالجة','Ask us about roast & process')}</b></div></div><div class="detail-actions"><button class="button dark" data-add="${c.id}">${t('أضف إلى اختياراتك +','Add to your selection +')}</button><button class="button" data-brew="${c.method}">${t('حضّر هذا المحصول ↗','Brew this coffee ↗')}</button></div><p class="collection-note">${t('الصور رسوم فنية للمحاصيل. تحقّق من تفاصيل الدفعة والأوزان والأسعار معنا عبر واتساب.','The artwork illustrates the origins. Confirm current lot details, pack sizes and prices with us on WhatsApp.')}</p>`;$('#coffeeDialog').showModal()}
function renderCart(){saveCart();$('#cartItems').innerHTML=cart.length?cart.map(item=>{const c=coffees.find(x=>x.id===item.id);return `<div class="cart-item"><div class="cart-item-top"><h3>${bi(c.name)}</h3><button class="remove-item" data-remove="${c.id}">${t('إزالة','Remove')}</button></div><div class="cart-options"><label>${t('الطحن','Grind')}<select data-grind="${c.id}">${grindOptions().map(([id,label])=>`<option value="${id}" ${id===item.grind?'selected':''}>${label}</option>`).join('')}</select></label><label>${t('عدد العبوات','Packs')}<input type="number" min="1" max="20" value="${item.qty}" data-qty="${c.id}"></label></div></div>`}).join(''):`<p class="empty-cart">${t('لم تختر محصولاً بعد. أضف ما يعجبك من المجموعة ثم أرسله لنا.','Your selection is empty. Add a coffee from the collection, then send it to us.')}</p><button class="button dark" id="browseFromCart">${t('اكتشف المحاصيل','Explore the collection')}</button>`;$('#sendOrder').hidden=!cart.length;updateOrderLink()}
function updateOrderLink(){const items=cart.map(x=>{const c=coffees.find(c=>c.id===x.id);return `${bi(c.name)} × ${x.qty} — ${grindOptions().find(g=>g[0]===x.grind)[1]}`}).join('\n');$('#sendOrder').href=wa(t('مرحباً سمراء، أرغب في الاستفسار عن:\n','Hello SAMRA, I would like to enquire about:\n')+items+t('\nيرجى تأكيد حجم العبوة، السعر، التوفّر وتفاصيل التوصيل.','\nPlease confirm pack sizes, prices, availability and delivery details.'))}
function renderQuiz(){const questions=[{title:t('أي نكهة تجذبك؟','What flavours draw you in?'),options:[['floral','✿',t('زهري وفاكهي','Floral & fruity')],['balanced','◐',t('حلو ومتوازن','Sweet & balanced')],['rich','◒',t('كاكاو ومكسرات','Cocoa & nuts')],['curious','✳',t('أحب الاكتشاف','Surprise me')]]},{title:t('كيف تحضّر قهوتك غالباً؟','How do you usually brew?'),options:[['filter','▽',t('فلتر / V60','Filter / V60')],['espresso','▤',t('إسبريسو','Espresso')],['press','▥',t('فرنش برس','French press')],['new','↗',t('أبدأ رحلتي الآن','I’m just getting started')]]},{title:t('كيف تحب أن تشربها؟','How do you like your cup?'),options:[['black','◉',t('سادة، بكل تفاصيلها','Black, all the details')],['milk','◌',t('مع الحليب','With milk')],['iced','◇',t('باردة ومنعشة','Iced & refreshing')],['both','✳',t('أحب التنويع','A little of everything')]]}];if(quizStep<3){const q=questions[quizStep];$('#quiz').innerHTML=`<div class="quiz-top"><span>${t('دليلك لقهوتك','YOUR COFFEE MATCH')}</span><span>0${quizStep+1} / 03</span></div><div class="quiz-progress">${[0,1,2].map(i=>`<span class="${i<=quizStep?'done':''}"></span>`).join('')}</div><h3>${q.title}</h3><div class="quiz-options">${q.options.map(([value,symbol,label])=>`<button class="quiz-option" data-answer="${value}"><span class="symbol" aria-hidden="true">${symbol}</span>${label}</button>`).join('')}</div>${quizStep?`<button class="quiz-back" id="quizBack">${t('→ السابق','← Back')}</button>`:''}`;}else{let id=answers[0]==='floral'?'guji':answers[0]==='rich'?'mogiana':'bombe';if(answers[0]==='floral'&&answers[2]==='iced')id='shalshali';if(answers[1]==='press'&&answers[0]==='rich')id='drugar';if(answers[2]==='milk')id=answers[0]==='rich'?'mogiana':'excelso';const c=coffees.find(c=>c.id===id);$('#quiz').innerHTML=`<div class="quiz-result"><p class="result-label">${t('بداية مقترحة لذوقك','YOUR SUGGESTED STARTING POINT')} / 03</p><h3>${bi(c.name)}</h3><div class="flavour-tags">${c.tags.map(a=>`<span>${bi(a)}</span>`).join('')}</div><p>${bi(c.desc)}</p><button class="button dark" data-detail="${c.id}">${t('اكتشف اقتراحك ↗','Explore your match ↗')}</button><br><button class="quiz-back" id="quizRestart">${t('جرّب من جديد','Find another match')}</button></div>`;}}
const config={v60:{min:10,max:40,dose:20,ratio:15,temp:92,time:'2:45–3:30',grind:['متوسط','Medium']},espresso:{min:14,max:22,dose:18,ratio:2,temp:93,time:'25–35 s',grind:['ناعم','Fine']},aeropress:{min:12,max:18,dose:15,ratio:14,temp:90,time:'2:00–2:30',grind:['متوسط ناعم','Medium-fine']},chemex:{min:20,max:45,dose:30,ratio:16,temp:94,time:'4:00–5:00',grind:['متوسط خشن','Medium-coarse']},french:{min:15,max:50,dose:30,ratio:15,temp:94,time:'4:00–5:00',grind:['خشن','Coarse']},cold:{min:30,max:100,dose:60,ratio:8,temp:4,time:'14–18 h',grind:['خشن','Coarse']}};
let timerInterval=null,timerStart=0,elapsed=0;
function resetTimer(){clearInterval(timerInterval);timerInterval=null;elapsed=0;$('#timer').textContent='00:00';$('#timerToggle').textContent=t('ابدأ','Start')}
function tick(){const seconds=Math.floor((elapsed+(timerInterval?Date.now()-timerStart:0))/1000);$('#timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function toggleTimer(){if(timerInterval){elapsed+=Date.now()-timerStart;clearInterval(timerInterval);timerInterval=null;$('#timerToggle').textContent=t('أكمل','Resume')}else{timerStart=Date.now();timerInterval=setInterval(tick,250);$('#timerToggle').textContent=t('إيقاف','Pause')}tick()}
function selectMethod(m){method=m;dose=config[m].dose;resetTimer();renderBrew()}
function recipe(){const c={...config[method]};if(method==='v60'){if(style==='floral'){c.ratio=16;c.temp=94}else if(style==='rich'){c.ratio=14;c.temp=92}else if(style==='iced'){c.ratio=15;c.temp=94}}const total=Math.round(dose*c.ratio),bloom=dose*3,ice=Math.round(total*.4),hot=total-ice;let steps=[],tip='';const step=(a,b,c,d)=>[t(a,b),t(c,d)];if(method==='v60'){
const iced=style==='iced',pourTotal=iced?hot:total,first=iced?Math.round(hot*.72):Math.round(total*.6);
steps=[step('جهّز الأدوات','Set the stage',`اغسل الفلتر بماء ساخن وتخلّص من ماء الغسل. ${iced?`ضع ${ice} غ من الثلج في الإبريق. `:''}أضف ${dose} غ بن ثم صفّر الميزان.`,`Rinse the filter and discard the rinse water. ${iced?`Put ${ice} g of ice in the server. `:''}Add ${dose} g of coffee, then tare the scale.`),step('الترطيب · 0:00–0:40','Bloom · 0:00–0:40',`صب ${bloom} غ ماء لتبليل البن كله. انتظر حتى 40 ثانية.`,`Pour ${bloom} g of water to wet all the grounds. Wait until 40 seconds.`),step('صبّ بهدوء','Pour gently',`ارفع قراءة الميزان إلى ${first} غ عند نحو 1:15، ثم إلى ${pourTotal} غ عند نحو 1:50. هذه أوزان تراكمية، وليست إضافية.`,`Bring the scale to ${first} g around 1:15, then ${pourTotal} g around 1:50. These are cumulative weights, not extra amounts.`),step('اتركها تقطر ثم تذوّق','Let it drain, then taste',iced?'اترك الماء يمر، ثم حرّك القهوة لإذابة الثلج. إذا انتهى التقطير سريعاً جداً، جرّب طحناً أنعم قليلاً.':'استهدف زمناً إجمالياً نحو 2:45–3:30، حسب كمية البن والطحن. حرّك الإبريق وتذوّق بعد أن تبرد قليلاً.',iced?'Let it drain, then swirl to melt the ice. If drawdown is very fast, try a slightly finer grind.':'Aim for roughly 2:45–3:30 total, depending on dose and grind. Swirl the server and taste as it cools.')];tip=t('تحتاج ميزاناً، فلتر V60، طاحونة وإبريق صب. للكميات الكبيرة استخدم حجماً مناسباً من الأداة.','You’ll need a scale, V60 filter, grinder and pouring kettle. Use a brewer size suited to your dose.');}
if(method==='espresso'){steps=[step('اطحن ووزّع','Grind & distribute',`أضف ${dose} غ إلى سلة تناسب هذه الجرعة. وزّع البن بالتساوي ثم اكبس بشكل مستوٍ.`,`Add ${dose} g to a basket designed for that dose. Distribute evenly and tamp level.`),step('استخلص بالوزن','Extract by weight',`ضع الكوب على الميزان. ابدأ التوقيت مع تشغيل المضخة، وأوقف الاستخلاص عند ${total} غ من المشروب.`,`Put the cup on a scale. Start timing with the pump and stop at ${total} g of espresso in the cup.`),step('اضبط ثم كرّر','Adjust & repeat','ابدأ بزمن 25–35 ثانية. إذا تدفّق سريعاً جداً جرّب طحناً أنعم، وإذا كان بطيئاً جداً جرّب أخشن. تذوّق قبل التعديل.','Start around 25–35 seconds. If the shot runs too fast, grind finer; if too slow, grind coarser. Taste before adjusting.'),step('استمتع سادة أو بالحليب','Enjoy black or with milk','للاتيه صغير، جرّب 120–150 غ حليب مع شوت مزدوج. للأمريكانو أضف الماء حسب ذوقك.','For a small latte, try 120–150 g of milk with a double shot. For an Americano, add water to taste.')];tip=t('النسبة هنا: وزن البن إلى وزن الإسبريسو الناتج، وليست كمية الماء في الخزان. حرارة 93°م نقطة بداية إذا كانت آلتك تسمح بضبطها.','This ratio is coffee dose to espresso output, not tank water. 93°C is a starting setting if your machine supports temperature adjustment.');}
if(method==='aeropress'){steps=[step('جهّز الأداة','Prepare the brewer','ثبّت الغطاء والفلتر جيداً. ضع الأداة بالطريقة العادية فوق كوب ثابت يتّسع للمشروب.','Secure the filter cap. Set the brewer upright on a sturdy mug large enough for your drink.'),step('أضف البن والماء','Add coffee & water',`أضف ${dose} غ بن ثم ${total} غ ماء. حرّك بهدوء لتبليل البن كله.`,`Add ${dose} g of coffee and ${total} g of water. Stir gently to wet all the grounds.`),step('انقع','Steep','أدخل المكبس قليلاً لإيقاف التقطير، وانتظر حتى 1:30 تقريباً.','Insert the plunger slightly to limit dripping and wait until about 1:30.'),step('اكبس ببطء','Press slowly','اكبس برفق لمدة 30–45 ثانية. لا تستخدم القوة إذا وجدت مقاومة كبيرة.','Press gently for 30–45 seconds. Do not force the plunger if you feel strong resistance.')];tip=t('وصفة نقع بالطريقة العادية. تحقّق من سعة موديل أداتك، ولا تتجاوز خط التعبئة.','An upright immersion recipe. Check your model’s capacity and stay below its fill line.');}
if(method==='chemex'){steps=[step('اغسل الفلتر','Rinse the filter','ضع الجانب ذي الطبقات الثلاث ناحية الفوهة. اغسل الفلتر جيداً وتخلّص من الماء.','Place the three-layer side of the filter toward the spout. Rinse thoroughly and discard the water.'),step('رطّب البن','Bloom',`أضف ${dose} غ بن وصب ${bloom} غ ماء. انتظر 45 ثانية.`,`Add ${dose} g coffee and pour ${bloom} g water. Wait 45 seconds.`),step('صب على دفعات','Pour in stages',`صب ببطء حتى قراءة ${Math.round(total*.6)} غ، ثم أكمل حتى ${total} غ. اترك مستوى الماء ينخفض قليلاً بين الصبّات.`,`Pour slowly to ${Math.round(total*.6)} g, then continue to ${total} g. Let the water level fall a little between pours.`),step('راقب التدفق','Watch the drawdown','ابدأ بزمن إجمالي 4–5 دقائق. إذا توقّف التصريف، تأكّد أن الفلتر لا يغلق مجرى الهواء.','Start around 4–5 minutes total. If drainage stalls, check that the filter is not blocking the air channel.')];tip=t('فلتر Chemex السميك يعطي كوباً صافياً. لا تضغط البن ولا تحرّك الفلتر أثناء الصب.','The thick Chemex filter makes a clear cup. Avoid compacting the grounds or moving the filter while pouring.');}
if(method==='french'){steps=[step('أضف البن والماء','Add coffee & water',`أضف ${dose} غ بن خشن، ثم ${total} غ ماء. حرّك برفق لتبليل البن.`,`Add ${dose} g of coarse coffee and ${total} g water. Stir gently to wet the grounds.`),step('انقع أربع دقائق','Steep for four minutes','ضع الغطاء دون ضغط المكبس. انتظر 4 دقائق.','Put the lid on without pressing the plunger. Wait four minutes.'),step('اكسر القشرة واكبس','Break the crust & press','حرّك السطح برفق، ثم اكبس ببطء. إذا واجهت مقاومة شديدة، توقّف ولا تضغط بقوة.','Stir the surface gently, then press slowly. If resistance is high, stop rather than forcing it.'),step('صب الكمية كاملة','Decant completely','صب القهوة في الأكواب أو إبريق آخر، حتى لا تبقى ملامسة للبن.','Pour into cups or another server so the coffee is no longer sitting on the grounds.')];tip=t('القوام أغنى من الفلتر الورقي. القليل من الرواسب طبيعي؛ اترك الرشفة الأخيرة إن كنت تفضّل كوباً أنظف.','Expect more body than a paper filter. A little sediment is normal; leave the last sip if you prefer a cleaner cup.');}
if(method==='cold'){steps=[step('اخلط','Combine',`ضع ${dose} غ بن خشن في وعاء نظيف مع ${total} غ ماء بارد. حرّك جيداً.`,`Combine ${dose} g coarse coffee with ${total} g cold water in a clean container. Stir well.`),step('انقع في الثلاجة','Refrigerate','غطّ الوعاء وانقعه في الثلاجة 14–18 ساعة. استخدم تذكيراً هاتفياً لهذا النقع الطويل.','Cover and steep in the refrigerator for 14–18 hours. Use a phone reminder for this long steep.'),step('صفِّ','Filter','صفِّ القهوة بمصفاة ثم فلتر ورقي إذا رغبت في كوب أقل رواسب.','Strain the coffee, then use a paper filter if you prefer less sediment.'),step('خفّف حسب الذوق','Dilute to taste','هذه وصفة مركّزة نسبياً. ابدأ بإضافة كمية مساوية من الماء أو الحليب، ثم عدّل حسب ذوقك.','This recipe is relatively concentrated. Start with equal parts coffee and water or milk, then adjust to taste.')];tip=t('الماء المعروض هو ماء النقع؛ كمية المشروب الناتجة أقل لأن البن يحتفظ بجزء من الماء. احتفظ بالمشروب مبرداً.','The water amount is for steeping; final drink yield is lower because the grounds retain water. Keep the finished drink refrigerated.');}
return{...c,total,bloom,ice,hot,steps,tip};}
function renderBrew(){const r=recipe();$('#methods').innerHTML=Object.keys(config).map(m=>`<button class="method ${method===m?'active':''}" data-method="${m}" aria-pressed="${method===m}">${icons[m]}<span>${methodNames()[m]}</span></button>`).join('');$('#styleControl').hidden=method!=='v60';$('#brewStyle').innerHTML=[['balanced',t('متوازن · 1:15','Balanced · 1:15')],['floral',t('خفيف وعطري · 1:16','Light & aromatic · 1:16')],['rich',t('غني · 1:14','Rich · 1:14')],['iced',t('مثلّج · 1:15','Japanese iced · 1:15')]].map(([v,l])=>`<option value="${v}" ${style===v?'selected':''}>${l}</option>`).join('');$('#dose').min=r.min;$('#dose').max=r.max;$('#dose').value=dose;$('#doseValue').textContent=dose+' g';$('#doseMin').textContent=r.min+' g';$('#doseMax').textContent=r.max+' g';$('#ratioNote').textContent=t('النسبة ','Ratio ')+`1:${r.ratio} · `+(method==='espresso'?t('بن : إسبريسو ناتج','coffee : espresso output'):t('بن : ماء','coffee : water'));$('#recipeTitle').textContent=methodNames()[method]+(method==='v60'&&style==='iced'?t(' المثلّج',' · Iced'):'');const waterLabel=method==='espresso'?t('الإسبريسو الناتج','Espresso output'):t('الماء','Water');const metrics=[[r.total+' g',waterLabel],[method==='cold'?t('ثلاجة','Chilled'):r.temp+'°C',t('الحرارة','Temperature')],[bi(r.grind),t('الطحن','Grind')],[r.time,t('الوقت المستهدف','Target time')]];if(method==='v60'&&style==='iced')metrics[0]=[r.hot+' + '+r.ice+' g',t('ماء ساخن + ثلج','Hot water + ice')];$('#metrics').innerHTML=metrics.map(([val,label])=>`<div class="metric"><b>${val}</b><small>${label}</small></div>`).join('');$('#recipeSteps').innerHTML=r.steps.map(([title,body])=>`<li><div><strong>${title}</strong><p>${body}</p></div></li>`).join('');$('#recipeTip').textContent=r.tip;$('#timerToggle').disabled=method==='cold';$('#timerToggle').textContent=timerInterval?t('إيقاف','Pause'):elapsed?t('أكمل','Resume'):t('ابدأ','Start')}
function renderAcademy(){const lessons=[['rinse',t('اغسل الفلتر','Rinse the filter'),t('اطوِ حافة الفلتر وضعه في الأداة، ثم اغسله بماء ساخن. تخلّص من ماء الغسل قبل إضافة البن.','Fold the paper seam, fit the filter and rinse with hot water. Discard the rinse water before adding coffee.')],['bloom',t('امنح البن وقتاً','Give it a moment'),t('بلّل كل البن واتركه 30–45 ثانية. الترطيب يساعد على خروج الغاز وتهيئة البن للصب التالي.','Wet all the grounds and wait 30–45 seconds. The bloom releases gas and prepares the bed for the next pour.')],['pour',t('صبّ بثبات','Keep the pour steady'),t('صب قريباً من سطح البن بحركة لطيفة. تابع الوزن على الميزان، وتجنّب صبّ الماء مباشرة على الورق.','Pour close to the coffee bed with a gentle motion. Follow the scale and avoid pouring directly onto the paper.')],['taste',t('تذوّق وتعلّم','Taste, then learn'),t('حرّك الإبريق قبل التقديم. تذوّق القهوة وهي دافئة ثم أبرد قليلاً؛ قد تكتشف نكهات لم تلاحظها أولاً.','Swirl the server before serving. Taste warm, then a little cooler; flavours may appear that you missed at first.')]];$('#lessons').innerHTML=lessons.map(([icon,title,text],i)=>`<article class="lesson"><div class="illustration"><span>0${i+1}</span>${icons[icon]}</div><h3>${title}</h3><p>${text}</p></article>`).join('');const fixes=[[t('حامضة أكثر من اللازم؟','Too sour or sharp?'),t('إذا كانت الحموضة حادّة والكوب فارغاً، جرّب طحناً أنعم قليلاً مع تثبيت باقي الوصفة. التحميص الفاتح قد يحتاج ماءً أسخن. الحموضة الفاكهية اللطيفة قد تكون جزءاً من طابع البن.','If acidity feels sharp and the cup hollow, try a slightly finer grind while keeping the recipe fixed. Lighter roasts may need hotter water. Pleasant fruit-like acidity can be part of the coffee’s character.')],[t('مرّة أو جافّة؟','Too bitter or drying?'),t('ابدأ بطحن أخشن قليلاً وقلّل التحريك الزائد. جرّب خفض الحرارة مع التحميص الداكن. نظافة الأدوات والماء المستخدم يؤثران أيضاً.','Start with a slightly coarser grind and less agitation. Try a lower temperature for darker roasts. Clean equipment and your brewing water also matter.')],[t('خفيفة أكثر مما تحب؟','Too weak or watery?'),t('قلّل الماء قليلاً مقابل نفس كمية البن، أو اختر أسلوب V60 الغني. إذا كانت خفيفة وحامضة معاً، جرّب تحسين الاستخلاص بطحن أنعم قبل زيادة الجرعة.','Use a little less water for the same dose, or select the rich V60 style. If it is both weak and sour, try improving extraction with a finer grind before increasing the dose.')],[t('كيف أحافظ على البن؟','How should I store my beans?'),t('احتفظ بالبن في عبوة محكمة، بعيداً عن الحرارة والضوء والرطوبة. اطحن قبل التحضير مباشرة، واسألنا عن تاريخ التحميص وفترة الراحة المناسبة للدفعة.','Store beans in a sealed container away from heat, light and moisture. Grind just before brewing, and ask us about the roast date and suitable resting time for the current lot.')]];$('#troubleshooting').innerHTML=fixes.map(([title,body])=>`<details><summary>${title}</summary><p>${body}</p></details>`).join('')}
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-ar][data-en]').forEach(el=>el.innerHTML=el.dataset[lang]);$('#language').textContent=lang==='ar'?'EN':'عربي';$('#language').setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');$('#contactWhatsApp').href=wa(t('مرحباً سمراء، أريد المساعدة في اختيار القهوة ومعرفة المحاصيل المتوفرة والأسعار.','Hello SAMRA, I’d like help choosing a coffee and checking availability and prices.'));$$('.close-dialog').forEach(b=>b.setAttribute('aria-label',t('إغلاق','Close')));renderCollection();renderQuiz();renderBrew();renderAcademy();renderCart();try{localStorage.setItem('samra-language',lang)}catch{}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filter=b.dataset.filter;renderCollection()}if(b.dataset.detail)showDetail(b.dataset.detail);if(b.dataset.add)addCart(b.dataset.add);if(b.dataset.method)selectMethod(b.dataset.method);if(b.dataset.answer){answers[quizStep]=b.dataset.answer;quizStep++;renderQuiz()}if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.brew){$('#coffeeDialog').close();selectMethod(b.dataset.brew);$('#brew').scrollIntoView()}if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);renderCart()}if(b.id==='quizBack'){quizStep--;renderQuiz()}if(b.id==='quizRestart'){quizStep=0;answers=[];renderQuiz()}if(b.id==='browseFromCart'){$('#cartDialog').close();$('#collection').scrollIntoView()}});
$('#language').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';translate()});
$('#openCart').addEventListener('click',()=>{renderCart();$('#cartDialog').showModal()});
$('#dose').addEventListener('input',e=>{dose=+e.target.value;renderBrew()});
$('#brewStyle').addEventListener('change',e=>{style=e.target.value;resetTimer();renderBrew()});
$('#timerToggle').addEventListener('click',toggleTimer);$('#timerReset').addEventListener('click',resetTimer);
$('#cartItems').addEventListener('input',e=>{if(e.target.dataset.grind){cart.find(x=>x.id===e.target.dataset.grind).grind=e.target.value}if(e.target.dataset.qty){const item=cart.find(x=>x.id===e.target.dataset.qty);item.qty=Math.min(20,Math.max(1,parseInt(e.target.value)||1));e.target.value=item.qty}saveCart();updateOrderLink()});
$('#copyRecipe').addEventListener('click',async()=>{const r=recipe();const text=`SAMRA · ${$('#recipeTitle').textContent}\n${dose} g ${t('بن','coffee')} · ${r.total} g ${method==='espresso'?t('إسبريسو ناتج','espresso output'):t('ماء','water')}\n${method==='cold'?t('ماء بارد','Cold water'):r.temp+'°C'} · ${bi(r.grind)} · ${r.time}\n`+r.steps.map(([a,b],i)=>`${i+1}. ${a}: ${b}`).join('\n');try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();if(!ok)throw Error('copy')}notify(t('تم نسخ الوصفة','Recipe copied'))}catch{notify(t('تعذّر النسخ. يمكنك تحديد الوصفة ونسخها يدوياً.','Could not copy. Select the recipe text and copy it manually.'))}});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('#year').textContent=new Date().getFullYear();translate();
